### PR TITLE
Add Chinese loacalization.

### PR DESCRIPTION
**Pull request by Yuchenjimmy**
This file is from the SC1 directory, not made by me.

### CODE REVIEW

**Review by speed2CZ — CHANGES_REQUESTED** [review]
This is the entire LOC file, the purpose of the coop LOC files is to add the mission mission traslations. This would overwrite any changes from the base game.

**Comment by Yuchenjimmy** [comment]
Ah, I would delet some of them, thank you.

**Comment by speed2CZ** [comment]
You can just make a new commit in this branch that removes the lines that are not mission related

**Comment by Yuchenjimmy** [comment]
Like this?

**Comment by speed2CZ** [comment]
Your last commit is deleting the file?

**Comment by Yuchenjimmy** [comment]
I deleted the first commit, which contains unrelated strings, does that affect the second commit?

speed2CZ ***@***.***> 於 2023年2月26日 下午6:39 寫道：

﻿

Your last commit is deleting the file?

**Pull request closed without merging**
